lib/fragment/cart/cart.dart
project update(current production)
-Fixed bug: replace same order trigger a loading dialog bug
=> 14/9/2023-YF (1.0.27)

android/app/build.gradle, language/en.json, language/ms.json, language/zh.json, lib/database/domain.dart, lib/database/pos_database.dart, lib/fragment/cart/cart_dialog.dart, lib/fragment/product/edit_product.dart, lib/fragment/setting/printer_setting.dart, lib/fragment/setting/receipt_setting.dart, lib/fragment/settlement/settlement_page.dart, lib/fragment/table/advanced_table/advanced_table_view.dart, lib/fragment/table/table_change_dialog.dart, lib/fragment/table/table_dialog.dart, lib/fragment/table/table_menu.dart, lib/object/table.dart, lib/page/second_display.dart
=> Latest version

lib/database/domain.dart, lib/database/pos_database.dart, lib/fragment/cart/cart.dart, lib/fragment/cart/remove_cart_dialog.dart, lib/fragment/report/cancellation_report.dart, lib/fragment/report/product_report.dart, lib/fragment/report/report_overview.dart, lib/fragment/settlement/settlement_dialog.dart, lib/object/pdf_format.dart, lib/object/receipt_layout.dart, pubspec.yaml
-Sync optimization
-Settlement bug hot fixed
-Report bug hot fixed
-Cancel production function minor change
=> 17/11/2023-YF (1.0.37)

lib/database/pos_database.dart, lib/fragment/cart/cart.dart, lib/fragment/payment/make_payment_dialog.dart, lib/fragment/payment/payment_success_dialog.dart, lib/fragment/product/product_order_dialog.dart, lib/notifier/cart_notifier.dart, lib/object/modifier_group.dart, lib/object/sync_record.dart, lib/page/home.dart, lib/page/second_display.dart, lib/utils/Utils.dart, pubspec.yaml
-Sync content load optimization
-Reactive ipay 88 to production
-Modifier group sequence number
-Rounding based on BNM standard
-Hot fix bug: All cart item clear if received data sync from sync record
=> 20/11/2023-YF (1.0.38, to be publish to production)

lib/database/pos_database.dart, lib/fragment/cart/adjust_quantity.dart, lib/fragment/cart/cart.dart, lib/fragment/cart/cart_dialog.dart, lib/fragment/cart/remove_cart_dialog.dart, lib/fragment/food/food_menu.dart, lib/fragment/payment/make_payment_dialog.dart, lib/fragment/payment/payment_select_dialog.dart, lib/fragment/payment/payment_success_dialog.dart, lib/fragment/product/product_order_dialog.dart, lib/fragment/setting/receipt_dialog.dart, lib/fragment/table/table_menu.dart, lib/object/print_receipt.dart, lib/object/receipt_layout.dart, lib/page/loading.dart, pubspec.yaml
- Category sequence
- Change second display default setting into disable
- Background sync: all cancel item, payment process
- Mobile layout optimization
- Receipt logo text now can print Chinese word
=> Pending Production

lib/object/search_delegate.dart, lib/page/loading.dart, pubspec.yaml
-Bug fixed:
1. Product search result did not appear
2. Some variant product cannot add to cart
=> 4/12/2023-YF (1.0.41)

language/en.json, language/ms.json, language/zh.json, lib/fragment/setting/hardware_setting.dart, lib/page/second_display.dart, pubspec.yaml
-New feature: reset second display function
-Fix second display bug
=> Hot fix bug- production merge

lib/fragment/product/product_order_dialog.dart, lib/fragment/qr_order/qr_main_page.dart, lib/fragment/setting/sync_dialog.dart, lib/fragment/settlement/settlement_dialog.dart, pubspec.yaml
1. New feature: During settlement now will sync all local data to cloud
2. Qr order kitchen list table number bug fixed
=> Current production (1.0.45)

language/en.json, language/ms.json, language/zh.json, lib/database/domain.dart, lib/database/pos_database.dart, lib/fragment/bill/refund_dialog.dart, lib/fragment/setting/sync_dialog.dart, lib/fragment/settlement/settlement_dialog.dart, lib/object/sync_to_cloud.dart, lib/page/pos_pin.dart, pubspec.yaml
New:
-remove 30 sync to cloud/from cloud
-optimize settlement manual sync to cloud
-Increase QR order sync timeout
Bug fixed:
-Multi refund
-Deleted printer/printer category cannot sync to cloud -Kitchen list sync
=> 03/01/2024 YF- to be publish

lib/database/pos_database.dart, lib/fragment/setting/sync_dialog.dart, lib/fragment/settlement/settlement_dialog.dart
Bug fixed:
-App setting branch id field default value
-Settlement gross sales null operator check
=> 04/01/2024 YF

language/en.json, language/ms.json, language/zh.json, lib/fragment/setting/sync_dialog.dart, lib/object/sync_to_cloud.dart
- Manual sync error handling optimize: show fail result when catch error
=> 29/01/2024 YF

lib/object/receipt_layout.dart, lib/page/loading.dart
- print chinese footer in receipt bug fixed
- loading getAllOrderDetail category_sqlite_id null issue
=> 08/02/2024 Chuah

android/build.gradle, lib/database/pos_database.dart, lib/fragment/payment/make_payment_dialog.dart, lib/fragment/payment/payment_success_dialog.dart, lib/fragment/report/cancel_modifier_report.dart, lib/fragment/report/cancellation_report.dart, lib/fragment/report/cash_record_report.dart, lib/fragment/report/category_report.dart, lib/fragment/report/daily_sales_report.dart, lib/fragment/report/dining_report.dart, lib/fragment/report/modifier_report.dart, lib/fragment/report/payment_report.dart, lib/fragment/report/print_report_page.dart, lib/fragment/report/product_edited_report.dart, lib/fragment/report/product_report.dart, lib/fragment/report/refund_report.dart, lib/fragment/report/report_overview.dart, lib/fragment/report/report_page.dart, lib/fragment/report/transfer_report.dart, lib/notifier/report_notifier.dart, lib/object/order.dart, lib/object/order_detail.dart, lib/object/pdf_format.dart, lib/object/report_class.dart
Bug fixed:
- Cash payment method take too long loading time
- Product report quantity sum error
- Report pdf did not generated
- Refund report show total tax amount properly
- Hide print function on edit product report
=> Yf version

lib/object/print_receipt.dart, pubspec.yaml
- kitchen list combine bug revert
=> merge with subscription 2

language/en.json, language/ms.json, language/zh.json, lib/database/pos_database.dart, lib/fragment/cart/adjust_price.dart, lib/fragment/cart/adjust_quantity.dart, lib/fragment/cart/cart.dart, lib/fragment/cart/remove_cart_dialog.dart, lib/fragment/payment/make_payment_dialog.dart, lib/fragment/qr_order/adjust_stock_dialog.dart, lib/fragment/qr_order/qr_main_page.dart, lib/fragment/report/report_page.dart, lib/fragment/setting/printer_dialog.dart, lib/fragment/setting/receipt_setting.dart, lib/fragment/setting/system_log_dialog.dart, lib/fragment/table/table_menu.dart, lib/main.dart, lib/notifier/cart_notifier.dart, lib/notifier/report_notifier.dart, lib/notifier/table_notifier.dart, lib/object/qr_order.dart, lib/object/qr_order_auto_accept.dart, lib/object/report_class.dart, lib/object/table.dart, lib/page/home.dart, pubspec.lock
New:
- Report new option: User now can select report based on opening balance or not
- Now when QR order auto accept will not refresh UI when there is a table in payment cart
- Table UI will refresh when there is no item in payment cart
Bug fixed:
- Widget keep rebuild when cart have auto apply promotion
- Auto accept QR stuck when user tap accept all in QR order page and jump to other page
- Table page UI refresh optimization
=> Widget rebuild

lib/database/pos_database.dart, pubspec.lock, pubspec.yaml
- product/cancel product report total quantity did not match
=> 02/09/2024 - bug fix

lib/object/sync_record.dart, pubspec.yaml
=> 19/09/2024 - Pending release

lib/custom_pin_dialog.dart, lib/fragment/setting/data_process_setting.dart, lib/main.dart, pubspec.lock
- Hide sync reset button
- required admin pin before sync to firestore
=> 20/11/2024 - Patch #6 ios & and

language/en.json, language/ms.json, language/zh.json, lib/fragment/cart/cart.dart, lib/fragment/cart/cart_dialog.dart, lib/fragment/cart/cart_dialog_function.dart, lib/fragment/custom_toastification.dart, lib/fragment/display_order/display_order.dart, lib/fragment/printing_layout/print_receipt.dart, lib/fragment/printing_layout/receipt_layout.dart, lib/fragment/settlement/cash_box_dialog.dart, lib/fragment/table/table_menu.dart, lib/main.dart, lib/notifier/cart_notifier.dart, lib/object/imin_lib.dart, lib/object/receipt_layout.dart, lib/object/search_delegate.dart, lib/object/server_action.dart, lib/page/pos_pin.dart, lib/second_device/cart_dialog_function.dart, lib/second_device/order/add_on_order.dart, lib/second_device/order/dine_in_order.dart, lib/second_device/order/not_dine_in_order.dart, lib/second_device/order/place_order.dart, lib/second_device/server.dart, pubspec.lock, pubspec.yaml
- Sub pos placed order failed auto clear cart bug
- Main/sub POS place order conflict 
- Main/sub pos merge/remove table conflict
- Reduce sub pos placed order tcp transmit data
- Bug fix: sub pos place order format exception
- Cash drawer now can open in non imin USB printer
- Bugfix: uncategorized product cannot load in sub pos
- Sub pos support order number
- Remove auto self test print everytime enter pos pin page
=> Sub pos bug v2

lib/database/pos_database.dart, lib/fragment/printing_layout/receipt_layout.dart, lib/object/receipt_layout.dart, pubspec.yaml
- Settlement receipt show staff sales
- rename some function
- Bump app version -> 1.1.44
=> 25/02/2025 - Production(1.1.44+156)

lib/fragment/food/food_setting.dart
- Specific category content in product page delayed bug fixed
=> 28/02/2025 - Patch for android & ios (1.1.44+156)+1

lib/database/pos_database.dart, lib/main.dart, pubspec.lock
- Bug fixed: settlement staff sales only show 1 staff sales record
- Bump path no -> 1
=> Staff sales bug fix
